configfile: "config/config.yaml"

SAMPLES = config["samples"]
RAW_DIR = config["paths"]["raw"]
RESULTS_DIR = config["paths"]["results"]

rule all:
    input:
        expand(f"{RESULTS_DIR}/qc/{{sample}}_fastqc.html", sample=SAMPLES)

include: "rules/qc.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"

